## Part 1: Preprocessing

In [7]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np 
import tensorflow as tf  
from tensorflow.keras.models import Model 
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

2025-04-17 19:17:37.363729: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [8]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [10]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

In [11]:
# Create a list of at least 10 column names to use as X data
x_columns = [
    'Age',
    'BusinessTravel',
    'Department',
    'DistanceFromHome',
    'Education',
    'EducationField',
    'EnvironmentSatisfaction',
    'HourlyRate',
    'JobInvolvement',
    'JobLevel'
]


# Create X_df using your selected columns
X_df = attrition_df[x_columns]


# Show the data types for X_df
print(X_df.dtypes)

Age                         int64
BusinessTravel             object
Department                 object
DistanceFromHome            int64
Education                   int64
EducationField             object
EnvironmentSatisfaction     int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
dtype: object


In [17]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

y = y_df['Attrition']
X_train, X_test, y_train, y_test = train_test_split(
    X_numeric, y, test_size=0.2, random_state=42, stratify=y
)



In [18]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
X_numeric = pd.get_dummies(X_df, drop_first=True)
print(X_numeric.head())
print(X_numeric.dtypes)

   Age  DistanceFromHome  Education  EnvironmentSatisfaction  HourlyRate  \
0   41                 1          2                        2          94   
1   49                 8          1                        3          61   
2   37                 2          2                        4          92   
3   33                 3          4                        4          56   
4   27                 2          1                        1          40   

   JobInvolvement  JobLevel  BusinessTravel_Travel_Frequently  \
0               3         2                             False   
1               2         2                              True   
2               2         1                             False   
3               3         1                              True   
4               3         1                             False   

   BusinessTravel_Travel_Rarely  Department_Research & Development  \
0                          True                              False   
1           

In [21]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)

print(X_train_scaled_df.head())



           Age  DistanceFromHome  Education  EnvironmentSatisfaction  \
1194  1.090194         -0.899915   1.064209                -0.658710   
128  -1.634828         -0.899915  -1.855332                 0.260202   
810   0.981193         -0.777610  -1.855332                -1.577622   
478  -1.307825          0.445433  -1.855332                -0.658710   
491   0.654191         -0.043784   2.037390                 1.179114   

      HourlyRate  JobInvolvement  JobLevel  BusinessTravel_Travel_Frequently  \
1194   -0.908436        1.795282  1.762189                         -0.486408   
128     1.694111        0.373564 -0.986265                         -0.486408   
810    -0.662913        0.373564  1.762189                         -0.486408   
478    -1.252169        0.373564 -0.986265                         -0.486408   
491     0.319180        0.373564 -0.070114                          2.055886   

      BusinessTravel_Travel_Rarely  Department_Research & Development  \
1194         

In [28]:
from sklearn.preprocessing import OneHotEncoder

X_train, X_test, y_train, y_test = train_test_split(
    X_numeric, y, test_size=0.2, random_state=42, stratify=y
)

dept_train = X_df.loc[X_train.index, ['Department']]
dept_test = X_df.loc[X_test.index, ['Department']]

# Create a OneHotEncoder for the Department column
dept_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder to the training data
dept_encoder.fit(dept_train)

# Create two new variables by applying the encoder
# to the training and testing data
X_train_dept_encoded = dept_encoder.transform(dept_train)
X_test_dept_encoded = dept_encoder.transform(dept_test) 


print(X_train_dept_encoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder to the training data
attrition_encoder.fit(y_train.values.reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
y_train_attrition_encoded = attrition_encoder.transform(y_train.values.reshape(-1, 1))
y_test_attrition_encoded = attrition_encoder.transform(y_test.values.reshape(-1, 1))

print(y_train_attrition_encoded)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


## Part 2: Create, Compile, and Train the Model

In [32]:
from tensorflow.keras.layers import Input, Dense

# Find the number of columns in the X training data.
input_dim = X_train_scaled_df.shape[1]
print("Number of columns in X training data:", input_dim)

# Create the input layer
input_layer = Input(shape=(input_dim,))

# Create at least two shared layers
shared_layer_1 = Dense(64, activation='relu')(input_layer)
shared_layer_2 = Dense(32, activation='relu')(shared_layer_1)

Number of columns in X training data: 16


In [33]:
# Create a branch for Department
# with a hidden layer and an output layer
dept_hidden = Dense(16, activation='relu', name='dept_hidden')(shared_layer_2)

# Create the hidden layer
# Create the output layer
dept_output = Dense(3, activation='softmax', name='dept_output')(dept_hidden)



In [34]:
# Create a branch for Attrition
# with a hidden layer and an output layer
attrition_hidden = Dense(16, activation='relu', name='attrition_hidden')(shared_layer_2)

# Create the hidden layer
# Create the output layer
attrition_output = Dense(1, activation='sigmoid', name='attrition_output')(attrition_hidden)



In [35]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output, attrition_output])

# Compile the model
model.compile(
    optimizer='adam',
    loss={
        'dept_output': 'categorical_crossentropy',
        'attrition_output': 'binary_crossentropy'
    },
    metrics={
        'dept_output': 'accuracy',
        'attrition_output': 'accuracy'
    }
)

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 16)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 64)        │      1,088 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 32)        │      2,080 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dept_hidden (Dense) │ (None, 16)        │        528 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 16)        │        528 │ dense_1[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dept_output (Dense) │ (None, 3)         │         51 │ dept_hidden[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 1)         │         17 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 4,292 (16.77 KB)

 Trainable params: 4,292 (16.77 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Train the model
model.compile(
    optimizer='adam',
    loss={
        'dept_output': 'categorical_crossentropy',
        'attrition_output': 'binary_crossentropy'
    },
    metrics={
        'dept_output': 'accuracy',
        'attrition_output': 'accuracy'
    }
)


history = model.fit(
    X_train_scaled,
    {
        'dept_output': X_train_dept_encoded,
        'attrition_output': y_train_numeric.values.reshape(-1, 1)
    },
    epochs=100,
    batch_size=32,
    validation_split=0.2
)


Epoch 1/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - attrition_output_accuracy: 0.6999 - attrition_output_loss: 0.6214 - dept_output_accuracy: 0.7774 - dept_output_loss: 0.8358 - loss: 1.4577 - val_attrition_output_accuracy: 0.8305 - val_attrition_output_loss: 0.4414 - val_dept_output_accuracy: 0.9619 - val_dept_output_loss: 0.4174 - val_loss: 0.8755
Epoch 2/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8389 - attrition_output_loss: 0.4431 - dept_output_accuracy: 0.9581 - dept_output_loss: 0.3393 - loss: 0.7825 - val_attrition_output_accuracy: 0.8305 - val_attrition_output_loss: 0.4145 - val_dept_output_accuracy: 0.9619 - val_dept_output_loss: 0.1632 - val_loss: 0.5975
Epoch 3/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8488 - attrition_output_loss: 0.4069 - dept_output_accuracy: 0.9594 - dept_output_loss: 0.1518 - loss: 0.5592 - val_attrition_output_accuracy: 0.8305 - val_attrition_output_loss: 0.4012 - val_dept_output_accurac

In [46]:
# Evaluate the model with the testing data
y_test_numeric = y_test.replace({'No': 0, 'Yes': 1}).astype('float32')


results = model.evaluate(
    X_test_scaled,
    {
        'dept_output': X_test_dept_encoded.astype('float32'),
        'attrition_output': y_test_numeric.values.reshape(-1, 1)
    }
)
for name, value in zip(model.metrics_names, results):
    print(f"{name}: {value:.4f}")


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.7849 - attrition_output_loss: 1.3304 - dept_output_accuracy: 0.9978 - dept_output_loss: 0.0186 - loss: 1.3597     
loss: 1.5384
compile_metrics: 0.0274
dept_output_loss: 1.4522
attrition_output_loss: 0.7653


/var/folders/7l/lzrcxgyj7wgdj6gs3nwf5xnc0000gn/T/ipykernel_23315/659068218.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y_test_numeric = y_test.replace({'No': 0, 'Yes': 1}).astype('float32')


In [48]:
# Print the accuracy for both department and attrition
results = model.evaluate(
    X_test_scaled,
    {
        'dept_output': X_test_dept_encoded.astype('float32'),
        'attrition_output': y_test_numeric.values.reshape(-1, 1)
    }
)

# Get metric names and print only the accuracy metrics
for name, value in zip(model.metrics_names, results):
    if 'accuracy' in name:
        print(f"{name}: {value:.4f}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.7849 - attrition_output_loss: 1.3304 - dept_output_accuracy: 0.9978 - dept_output_loss: 0.0186 - loss: 1.3597     


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy is not always the best metric for this data, especially for the Attrition prediction. Attrition datasets are often imbalanced, with many more "No" (not leaving) than "Yes" (leaving) cases. In such cases, a model can achieve high accuracy by always predicting the majority class, but this does not mean it is good at identifying employees who actually leave.
2. Attrition output:
I used a sigmoid activation function for the Attrition output layer because this is a binary classification problem ("Yes" or "No"). Sigmoid outputs a probability between 0 and 1, which is ideal for binary outcomes.


Department output:
I used a softmax activation function for the Department output layer because this is a multi-class classification problem (predicting one of several departments). Softmax outputs a probability distribution across all possible classes, ensuring the probabilities sum to 1.

3. Address class imbalance:
Use class weighting, oversampling (e.g., SMOTE), or undersampling to help the model learn from rare events like attrition.

Tune hyperparameters:
Experiment with the number of layers, units per layer, learning rate, batch size, and activation functions.

Feature engineering:
Create new features, select the most relevant features, or use domain knowledge to improve input data.